[package]
name = "git-autosnap"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.45", features = ["derive"] }
git2 = "0.20.2"
miette = "7.6.0"
tokio = "1.47.1"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
watchexec = "8.0.1"
watchexec-events = "6.0.0"
watchexec-filterer-ignore = "7.0.0"
ignore-files = "3.0.4"
watchexec-signals = "5.0.0"

[dev-dependencies]
assert_cmd = "2.0.17"
predicates = "3.1.3"
