unstable_features = true

imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_impl_items = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
